config/routes.rb
Rails.application.routes.draw do
  get '/profile', to: 'profile#show'

  get 'profile/settings'

  get 'settings/profile', to: 'settings#profile'

  get  'settings/password', to: 'settings#password'
  post 'settings/password', to: 'settings#save_password'

  get 'settings/2fa', to: 'settings#two_factor'

  get 'settings/enable-2fa', to: 'settings#show_enable_two_factor'
  post 'settings/enable-2fa', to: 'settings#enable_two_factor'

  get 'settings/disable-2fa', to: 'settings#show_disable_two_factor'
  post 'settings/disable-2fa', to: 'settings#disable_two_factor'

  get 'settings', to: 'settings#show'

  root 'home#index'
  get '/login', to: 'login#index'
  get '/login/two_factor', to: 'login#two_factor'
  post '/login', to: 'session#create'
  post '/two_factor', to: 'session#two_factor'
  get '/logout', to: 'session#destroy'

  resources :users
  resources :victims
  resources :offenses

  get '/offenses/type/:offense_type_slug', to: 'offenses#index_with_offense_type', as: :offenses_type

end

app/models/victim.rb
class Victim < ActiveRecord::Base
  has_many :comments
  has_many :offenses
end

app/controllers/victims_controller.rb
class VictimsController < ApplicationController
  before_action :set_victim, only: [:show, :edit, :update, :destroy]
  before_filter :authorize!

  # GET /victims
  # GET /victims.json
  def index
    @victims = Victim.all
  end

  # GET /victims/1
  # GET /victims/1.json
  def show
  end

  # GET /victims/new
  def new
    @victim = Victim.new
  end

  # GET /victims/1/edit
  def edit
  end

  # POST /victims
  # POST /victims.json
  def create
    @victim = Victim.new(victim_params)

    respond_to do |format|
      if @victim.save
        format.html { redirect_to victims_url, notice: 'Victim was successfully created.' }
        format.json { render :show, status: :created, location: @victim }
      else
        format.html { render :new }
        format.json { render json: @victim.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /victims/1
  # PATCH/PUT /victims/1.json
  def update
    respond_to do |format|
      if @victim.update(victim_params)
        format.html { redirect_to victims_url, notice: 'Victim was successfully updated.' }
        format.json { render :show, status: :ok, location: @victim }
      else
        format.html { render :edit }
        format.json { render json: @victim.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /victims/1
  # DELETE /victims/1.json
  def destroy
    @victim.destroy
    respond_to do |format|
      format.html { redirect_to victims_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_victim
      @victim = Victim.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def victim_params
      params.require(:victim).permit(:user_id, :name, :reason, :ip_address)
    end
end

app/helpers/victims_helper.rb
module VictimsHelper
  include Memoizable

  def offenses
    @victim.offenses
  end
  memoize :offenses

  def comments
    @victim.comments
  end
  memoize :comments

  def known_ip_addresses
    offenses.map do |offense|
      unless offense.ip_address.blank?
        link_to(offense.ip_address, offense.trace_ip_address_url, target: '_blank')
      end
    end
  end
  memoize :known_ip_addresses

end

app/views/victims/_form.html.slim
= form_for @victim, html: {class: 'form-horizontal'} do |f|
  - if @victim.errors.any?
    #error_explanation
      h2 = "#{pluralize(@victim.errors.count, "error")} prohibited this victim from being saved:"
      ul
        - @victim.errors.full_messages.each do |message|
          li = message

  .form-group
    = f.label :name, class: 'col-sm-1 control-label'
    .col-sm-5
      = f.text_field :name, class: 'form-control'

  .form-group
    .col-sm-offset-1.col-sm-11
      => f.submit 'Save', class: 'btn btn-primary'
      button.btn.btn-danger type="reset" Reset

app/views/victims/edit.html.slim
h2 Editing victim

== render 'form'


= link_to 'Show', @victim
' |
= link_to 'Back', victims_path
' |
= link_to 'Delete', @victim, data: {:confirm => 'Are you sure?'}, :method => :delete

app/views/victims/index.html.slim
h2 Victim list

table.table.table-striped.table-condensed
  thead
    tr
      th.edit
      th.date Date
      th.name Name
      th.offenses Offenses
      th.comments Comments

  tbody
    - @victims.each do |victim|
      tr
        td.edit
          a href=victim_path(victim)
            span.glyphicon.glyphicon-eye-open
          ' &nbsp;
          a href=edit_victim_path(victim)
            span.glyphicon.glyphicon-edit

        td = victim.created_at.strftime('%d.%m.%Y')
        td = victim.name
        td = victim.offenses.count
        td = victim.comments.count

= link_to 'New Victim', new_victim_path

app/views/victims/new.html.slim
h2 New victim

== render 'form'

app/views/victims/show.html.slim
h2 = @victim.name

- if known_ip_addresses.any?
  p
    strong Known IP addresses:
    ==< known_ip_addresses.join(', ')

- if offenses.any?
  h3 Offenses
  table.table.table-striped.table-condensed
    thead
      tr
        th.date Date
        th.user User
        th.type Type
        th.name Name
        th.reason Reason

    tbody
      - offenses.each do |offense|
        tr
          td = offense.created_at.strftime('%d.%m.%Y')
          td = link_to(offense.user.name, user_url(offense.user))
          td = link_to(offense.offense_type.name, offenses_type_url(offense.offense_type.slug))
          td = offense.name
          td = link_to(offense.reason, offense.url, target: '_blank')

- if comments.any?
  h3 Comments
  table.table
    - comments.each do |comment|
      tr
        td.date = comment.created_at.strftime('%d.%m.%Y')
        td.name = comment.user.name
        td.body = comment.body

= link_to 'Edit', edit_victim_path(@victim)
'|
= link_to 'Back', victims_path