config/routes.rb
Rails.application.routes.draw do
  get '/profile', to: 'profile#show'

  get 'profile/settings'

  get 'settings/profile', to: 'settings#profile'

  get  'settings/password', to: 'settings#password'
  post 'settings/password', to: 'settings#save_password'

  get 'settings/2fa', to: 'settings#two_factor'

  get 'settings/enable-2fa', to: 'settings#show_enable_two_factor'
  post 'settings/enable-2fa', to: 'settings#enable_two_factor'

  get 'settings/disable-2fa', to: 'settings#show_disable_two_factor'
  post 'settings/disable-2fa', to: 'settings#disable_two_factor'

  get 'settings', to: 'settings#show'

  root 'home#index'
  get '/login', to: 'login#index'
  get '/login/two_factor', to: 'login#two_factor'
  post '/login', to: 'session#create'
  post '/two_factor', to: 'session#two_factor'
  get '/logout', to: 'session#destroy'

  resources :users
  resources :victims
  resources :offenses

  get '/offenses/type/:offense_type_slug', to: 'offenses#index_with_offense_type', as: :offenses_type

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_one_time_password

  has_many :offenses
  has_many :comments
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_filter :authorize!, except: [:new, :create]
  layout :user_layout

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show

  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to users_url, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to users_url, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

private
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:name, :email, :password)
  end

  def user_layout
    if user_logged_in?
      'application'
    else
      'login'
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.slim
= form_for @user, html: {class: 'form-horizontal'}  do |f|
  - if @user.errors.any?
    #error_explanation
      h2 = "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      ul
        - @user.errors.full_messages.each do |message|
          li = message

  .form-group
    = f.label :name, class: 'col-sm-1 control-label'
    .col-sm-5
      = f.text_field :name, class: 'form-control'
  .form-group
    = f.label :email, class: 'col-sm-1 control-label'
    .col-sm-5
      = f.text_field :email, class: 'form-control'
  .form-group
    = f.label :password, class: 'col-sm-1 control-label'
    .col-sm-5
      = f.password_field :password, class: 'form-control'
  .form-group
    .col-sm-offset-1.col-sm-11
      => f.submit 'Save', class: 'btn btn-primary'
      button.btn.btn-danger type="reset" Reset

app/views/users/edit.html.slim
h2 Editing user

== render 'form'

= link_to 'Show', @user
'|
= link_to 'Back', users_path

app/views/users/index.html.slim
h2 User list

table.table.table-striped.table-condensed
  thead
    tr
      th.edit
      th Name
      th Email
      th Offenses

  tbody
    - @users.each do |user|
      tr
        td.edit
          a href=user_path(user)
            span.glyphicon.glyphicon-eye-open
          ' &nbsp;
          a href=edit_user_path(user)
            span.glyphicon.glyphicon-edit

        td = user.name
        td = user.email
        td = user.offenses.count

= link_to 'New User', new_user_path

app/views/users/new.html.slim
h2 New user

== render 'form'

app/views/users/show.html.slim
p#notice = notice

p
  strong Name:
  = @user.name
p
  strong Email:
  = @user.email

= link_to 'Edit', edit_user_path(@user)
'|
= link_to 'Back', users_path