config/routes.rb
Rails.application.routes.draw do
  get '/profile', to: 'profile#show'

  get 'profile/settings'

  get 'settings/profile', to: 'settings#profile'

  get  'settings/password', to: 'settings#password'
  post 'settings/password', to: 'settings#save_password'

  get 'settings/2fa', to: 'settings#two_factor'

  get 'settings/enable-2fa', to: 'settings#show_enable_two_factor'
  post 'settings/enable-2fa', to: 'settings#enable_two_factor'

  get 'settings/disable-2fa', to: 'settings#show_disable_two_factor'
  post 'settings/disable-2fa', to: 'settings#disable_two_factor'

  get 'settings', to: 'settings#show'

  root 'home#index'
  get '/login', to: 'login#index'
  get '/login/two_factor', to: 'login#two_factor'
  post '/login', to: 'session#create'
  post '/two_factor', to: 'session#two_factor'
  get '/logout', to: 'session#destroy'

  resources :users
  resources :victims
  resources :offenses

  get '/offenses/type/:offense_type_slug', to: 'offenses#index_with_offense_type', as: :offenses_type

end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  before_action :set_user
  before_filter :authorize!

  def show
  end


  def profile

  end

  def password

  end

  def two_factor

  end

  def save_password
    unless @user.authenticate(params[:current_password])
      flash.alert = 'Invalid current password!'
      return redirect_to :back
    end

    unless params[:new_password] == params[:confirm_new_password]
      flash.alert = 'Passwords don\'t match'
      return redirect_to :back
    end

    @user.update(password: params[:new_password])
    @user.save

    redirect_to settings_path
  end

  def show_enable_two_factor
    if !@user.use_otp?
      @user.update_attribute(:otp_secret_key, ROTP::Base32.random_base32)
      @qr = RQRCode::QRCode.new(@user.provisioning_uri('HuntThemDown'), :level => :h)
    else
      redirect_to settings_2fa_path
    end
  end

  def enable_two_factor
    if user.authenticate_otp(params[:confirmation_otp])
      @user.update_attribute(:use_otp, true)
      flash.notice = '2FA enabled successfully!'

      redirect_to settings_2fa_path
    else
      redirect_to settings_enable_2fa_path
    end
  end

  def show_disable_two_factor
    unless @user.use_otp?
      redirect_to settings_2fa_path
    end
  end

  def disable_two_factor
    if user.authenticate_otp(params[:confirmation_otp])
      @user.update_attribute(:use_otp, false)
      flash.notice = '2FA disabled successfully!'

      redirect_to settings_2fa_path
    else
      redirect_to settings_disable_2fa_path
    end
  end

  private

  def set_user
    @user = User.find_by(id: user.id)
  end
end

app/views/settings/password.html.slim
.panel.panel-default
  .panel-heading Change password
  .panel-body
    = form_tag settings_password_path, method: 'post', class: 'form-horizontal'
      - flash.each do |key, value|
        p.alert.alert-danger = value

      .form-group
        = label :current_password, 'Current password', class: 'col-sm-2 control-label'
        .col-sm-5
          = password_field_tag :current_password, nil, class: 'form-control', autofill: 'current-password'

      .form-group
        = label :new_password, 'New password', class: 'col-sm-2 control-label'
        .col-sm-5
          = password_field_tag :new_password, nil, class: 'form-control', autofill: 'new-password'

      .form-group
        = label :confirm_new_password, 'Confirm new password', class: 'col-sm-2 control-label'
        .col-sm-5
          = password_field_tag :confirm_new_password, nil, class: 'form-control', autofill: 'new-password'

      .form-group
        .col-sm-offset-2.col-sm-11
          button.btn.btn-primary Save
          | &nbsp;
          button.btn.btn-danger type="reset" Reset

app/views/settings/profile.html.slim
h1 Profile#settings_common
p Find me in app/views/profile/profile.html.slim

app/views/settings/show.html.slim
h1 Profile#settings
p Find me in app/views/profile/show.html.slim

ul
  li = link_to('Change password', settings_password_path)
  li = link_to('Change 2FA settings', settings_2fa_path)

app/views/settings/show_disable_two_factor.html.slim
.panel.panel-default
  .panel-heading Disable two-factor authentication
  .panel-body
    .list-group
      li.list-group-item
        h3 Enter a 6-digit code the app generates to disable two-factor authentication
        = form_tag settings_enable_2fa_path, method: 'post', class: 'form-inline', :'ng-controller' => 'HuntThemDown.TwoFactorAuthController as TwoFA_Ctrl'
          - flash.each do |key, value|
            p.alert.alert-danger = value

          .form-group
            = text_field_tag :confirmation_otp, nil, class: 'form-control', placeholder: 'Authentication Code', :'ng-model' => 'otp', maxlength: 6

          button.btn.btn-success ng-disabled="!TwoFA_Ctrl.isFormSubmittable()" Disable

app/views/settings/show_enable_two_factor.html.slim
.panel.panel-default
  .panel-heading Enable two-factor authentication
  .panel-body
    .list-group
      li.list-group-item
        h3 1. Download one of these apps
        ul
          li
            | iOS
            ul
              li = link_to('Google Authenticator', 'https://itunes.apple.com/de/app/google-authenticator/id388497605', target: '_blank')
              li = link_to('Duo Mobile', 'https://itunes.apple.com/us/app/duo-mobile/id422663827', target: '_blank')

          li
            | Android
            ul
              li = link_to('Google Authenticator', 'https://play.google.com/store/apps/details?id=com.google.android.apps.authenticator2', target: '_blank')
              li = link_to('Duo Mobile', 'https://play.google.com/store/apps/details?id=com.duosecurity.duomobile', target: '_blank')

          li
            | Windows Phone
            ul
              li = link_to('Authenticator', 'https://www.microsoft.com/de-de/store/apps/authenticator/9nblggh09llf', target: '_blank')

      li.list-group-item style="overflow: hidden"
        div style="float: left"
          h3 2. Configuring the app
          p.text-info Open your authentication app and add your Hunt Them Down account by scanning the QR-code to the right.
        table.qr
          - @qr.modules.each_index do |x|
            tr
              - @qr.modules.each_index do |y|
                - if @qr.dark?(x, y)
                  td.black
                - else
                  td.white

      li.list-group-item
        h3 3. Enter the the 6-digit code the app generates <small>Beware: the codes will change every 30 seconds</small>
        = form_tag settings_enable_2fa_path, method: 'post', class: 'form-inline', :'ng-controller' => 'HuntThemDown.TwoFactorAuthController as TwoFA_Ctrl'
          - flash.each do |key, value|
            p.alert.alert-danger = value

          .form-group
            = text_field_tag :confirmation_otp, nil, class: 'form-control', placeholder: 'Authentication Code', :'ng-model' => 'otp', maxlength: 6

          button.btn.btn-success ng-disabled="!TwoFA_Ctrl.isFormSubmittable()" Enable

app/views/settings/two_factor.html.slim
h1 Profile#settings_two_factor
p Find me in app/views/profile/two_factor.html.slim

- if !@user.use_otp?
  = link_to('Enable 2FA', settings_enable_2fa_path)
- else
  = link_to('Disable 2FA', settings_disable_2fa_path)