config/routes.rb
Rails.application.routes.draw do
  get '/profile', to: 'profile#show'

  get 'profile/settings'

  get 'settings/profile', to: 'settings#profile'

  get  'settings/password', to: 'settings#password'
  post 'settings/password', to: 'settings#save_password'

  get 'settings/2fa', to: 'settings#two_factor'

  get 'settings/enable-2fa', to: 'settings#show_enable_two_factor'
  post 'settings/enable-2fa', to: 'settings#enable_two_factor'

  get 'settings/disable-2fa', to: 'settings#show_disable_two_factor'
  post 'settings/disable-2fa', to: 'settings#disable_two_factor'

  get 'settings', to: 'settings#show'

  root 'home#index'
  get '/login', to: 'login#index'
  get '/login/two_factor', to: 'login#two_factor'
  post '/login', to: 'session#create'
  post '/two_factor', to: 'session#two_factor'
  get '/logout', to: 'session#destroy'

  resources :users
  resources :victims
  resources :offenses

  get '/offenses/type/:offense_type_slug', to: 'offenses#index_with_offense_type', as: :offenses_type

end

app/controllers/offenses_controller.rb
class OffensesController < ApplicationController
  before_action :set_offense, only: [:show, :edit, :update, :destroy]
  before_filter :authorize!

  # GET /offenses
  # GET /offenses.json
  def index
    @offenses = Offense.all
  end

  # GET /offenses/warnings
  # GET /offenses/warnings.json
  def index_with_offense_type
    @offense_type = OffenseType.find_by(slug: params[:offense_type_slug])
    @offenses = Offense.where(offense_type: @offense_type)

    render 'index'
  end

  # GET /offenses/1
  # GET /offenses/1.json
  def show
  end

  # GET /offenses/new
  def new
    @offense = build_offense
  end

  # GET /offenses/1/edit
  def edit
  end

  # POST /offenses
  # POST /offenses.json
  def create
    @offense = Offense.new(offense_params)

    respond_to do |format|
      if @offense.save
        format.html { redirect_to offenses_url, notice: 'Offense was successfully created.' }
        format.json { render :show, status: :created, location: @offense }
      else
        format.html { render :new }
        format.json { render json: @offense.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /offenses/1
  # PATCH/PUT /offenses/1.json
  def update
    respond_to do |format|
      if @offense.update(offense_params)
        format.html { redirect_to offenses_url, notice: 'Offense was successfully updated.' }
        format.json { render :show, status: :ok, location: @offense }
      else
        format.html { render :edit }
        format.json { render json: @offense.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /offenses/1
  # DELETE /offenses/1.json
  def destroy
    @offense.destroy
    respond_to do |format|
      format.html { redirect_to offenses_url }
      format.json { head :no_content }
    end
  end

private
  # Use callbacks to share common setup or constraints between actions.
  def set_offense
    @offense = Offense.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def offense_params
    parameters = params.require(:offense).permit(:user_id, :victim_id, :victim, :offense_type_id, :name, :duration, :reason, :url, :ip_address)

    victim = parameters.fetch('victim', nil)

    if victim
      parameters['victim'] = find_or_create_victim(victim)
    end

    parameters
  end

  def find_or_create_victim(name)
    victim = Victim.find_by(name: name)

    unless victim
      victim = Victim.create(name: name)
    end

    victim
  end

  def build_offense
    parameters = params.permit(:offense_type_id, :name, :url, :ip_address)

    Offense.new(parameters)
  end
end

app/helpers/offenses_helper.rb
module OffensesHelper
end

app/views/offenses/_form.html.slim
= form_for @offense, html: {class: 'form-horizontal', :'ng-controller' => 'HuntThemDown.OffenseController as offenseCtrl'} do |f|
  - if @offense.errors.any?
    #error_explanation
      h2 = "#{pluralize(@offense.errors.count, "error")} prohibited this offense from being saved:"
      ul
        - @offense.errors.full_messages.each do |message|
          li = message

  = f.hidden_field :user_id, value: user.id

  .form-group
    = f.label :victim, class: 'col-sm-2 control-label'
    .col-sm-5
      = f.text_field :victim, class: 'form-control', :'ng-model' => 'offense.victim', typeahead: 'victim for victim in offenseCtrl.getVictims() | filter:{name:$viewValue} | limitTo:8', autocomplete: 'off'

  .form-group
    = f.label :offense_type, class: 'col-sm-2 control-label'
    .col-sm-5
      = collection_select(:offense, :offense_type_id, OffenseType.all, :id, :name, {}, class: 'form-control')

  .form-group
    = f.label :user, class: 'col-sm-2 control-label'
    .col-sm-5
      = collection_select(:offense, :user_id, User.all, :id, :name, {}, class: 'form-control')

  .form-group
    = f.label :name, class: 'col-sm-2 control-label'
    .col-sm-5
      = f.text_field :name, class: 'form-control'

  .form-group
    = f.label :reason, class: 'col-sm-2 control-label'
    .col-sm-5
      = f.text_field :reason, class: 'form-control'

  .form-group
    = f.label :url, class: 'col-sm-2 control-label'
    .col-sm-5
      = f.text_field :url, class: 'form-control'

  .form-group
    = f.label :ip_address, class: 'col-sm-2 control-label'
    .col-sm-5
      = f.text_field :ip_address, class: 'form-control'

  .form-group
    = f.label :hostname, class: 'col-sm-2 control-label'
    .col-sm-5
      = f.text_field :hostname, class: 'form-control'

  .form-group
    .col-sm-offset-2.col-sm-11
      => f.submit 'Save', class: 'btn btn-success'
      button.btn.btn-danger type="reset" Reset

app/views/offenses/edit.html.slim
h2 Editing offense

== render 'form'


= link_to 'Show', @offense
' |
= link_to 'Back', offenses_url
' |
= link_to 'Delete', @offense, data: {:confirm => 'Are you sure?'}, :method => :delete

app/views/offenses/index.html.slim
- if @offense_type
  h2 = "#{@offense_type.name} list"
- else
  h2 Offenses list

table.table.table-striped.table-condensed
  thead
    tr
      th.edit
      th.date Date
      th.user User
      th.victim Victim
      th.name Name
      th.reason Reason
      th.ip_address IP address

  tbody
    - @offenses.each do |offense|
      tr
        td.edit
          a href=edit_offense_path(offense)
            span.glyphicon.glyphicon-edit

        td = offense.created_at.strftime('%d.%m.%Y')
        td = link_to(offense.user.name, user_url(offense.user))
        td = link_to(offense.victim.name, victim_url(offense.victim))
        td = offense.name
        td = link_to(offense.reason, offense.url, target: '_blank')
        td
          => link_to(offense.ip_address, offense.trace_ip_address_url, target: '_blank')
          = offense.hostname

= link_to 'New offense', new_offense_url

app/views/offenses/new.html.slim
h2 New offense

== render 'form'

app/views/offenses/show.html.slim
p#notice = notice

p
  strong Name:
  = @offense.name
p
  strong Reason:
  = @offense.reason
p
  strong Ip:
  = @offense.ip_address

= link_to 'Edit', edit_offense_path(@offense)
'|
= link_to 'Back', offenses_url